manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: robomaster-dlmu
      url-base: https://github.com/RoboMaster-DLMU-CONE
    - name: origin
      url-base: https://github.com/120MF

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_stm32

    - name: one-framework
      remote: robomaster-dlmu
      revision: main
      path: modules/lib/one-framework
      import: true


    - name: yandy-gimbal
      url: https://github.com/120MF/yandy-gimbal
      path: modules/lib/nodes/yandy-gimbal
      revision: main

  self:
    path: yandy-gimbal
